-- This file defines the schema for the airline database.

CREATE TABLE AIRPLANES (
    AIRCRAFT_REGISTRATION VARCHAR(10) PRIMARY KEY,
    BUILD_DATE DATE NOT NULL,
    SEATS INT NOT NULL
);

CREATE TABLE PASSENGERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    TELEPHONE VARCHAR(15)
);

CREATE TABLE ROUTES (
    ROUTE_CODE VARCHAR(10) PRIMARY KEY,
    ORIGIN VARCHAR(100) NOT NULL,
    DESTINATION VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE TICKETS (
    TICKET_ID INT PRIMARY KEY,
    PASSENGER_ID INT NOT NULL,
    ROUTE_CODE VARCHAR(10) NOT NULL,
    AIRCRAFT_ID VARCHAR(10) NOT NULL,
    FLIGHT_DATE DATE NOT NULL,
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(ID),
    FOREIGN KEY (ROUTE_CODE) REFERENCES ROUTES(ROUTE_CODE),
    FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRPLANES(AIRCRAFT_REGISTRATION)
);